convert search --param-search option into it's own command "match"
using a separate command instead of the awkward switch makes the ui more straight forward
and the code cleaner.

diff --git a/lms_bash b/lms_bash
--- a/lms_bash
+++ b/lms_bash
@@ -113,24 +113,39 @@ EOF
     
     export -f lms_search_and_enqueue
     local searchargs
+    # command starts as 'search' (text searching), fzf drilldown actions use 'match'
+    # because they use matches against the selected id.
+    local command=search
     while [[ "$1" == -* ]]; do
-	    searchargs="$1 $searchargs"
-	    shift
+        case "$1" in
+            -drilldown)
+                command=match
+                ;;
+            *)
+            searchargs="$1 $searchargs"
+            ;;
+        esac
+        shift
     done
+    if [[ $# -eq 0 ]]; then
+        echo "lms_search_and_enqueue: missing search type (artists|albums|tracks)" >&2
+        return 1
+    fi
+    
     local stype=$1
     local action
     case $stype in
 	 artists )
-         action="execute:(lms_search_and_enqueue -r albums artist_id:{1})"
+         action="execute:(lms_search_and_enqueue -drilldown albums artist_id:{1})"
 	     ;;
 	 albums )
-	     action="execute:(lms_search_and_enqueue -r tracks album_id:{1})"
+	     action="execute:(lms_search_and_enqueue -drilldown tracks album_id:{1})"
 	     ;;
 	 * )
 	     action="execute-silent:(ignore)"
     esac
-    #--header=$stype $_LMS_EXTRA_ARGS  \
-    lms $playerargs $searchargs search $stype "${@:2}"  \
+    
+    lms $playerargs $searchargs "$command" $stype "${@:2}"  \
 	|  \
 	fzf --tac -m --with-nth="2.." --no-hscroll  \
 	    --prompt="$stype> "  \
